import { db } from '@/db';
import { jobCompletions } from '@/db/schema';

async function main() {
    const sampleJobCompletions = [
        {
            orderId: 1,
            subcontractorId: 1,
            timeSlotId: 1,
            completionPhotos: ["https://example.com/photos/job1-photo1.jpg", "https://example.com/photos/job1-photo2.jpg", "https://example.com/photos/job1-photo3.jpg"],
            signatureData: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
            gpsLat: 47.6062,
            gpsLng: -122.3321,
            gpsTimestamp: new Date('2024-12-20T10:30:00Z').toISOString(),
            completionNotes: "Customer very satisfied with the installation. All equipment working perfectly.",
            completedAt: new Date('2024-12-20T10:30:00Z').toISOString(),
            customerSatisfaction: 5,
        },
        {
            orderId: 2,
            subcontractorId: 2,
            timeSlotId: 2,
            completionPhotos: ["https://example.com/photos/job2-photo1.jpg", "https://example.com/photos/job2-photo2.jpg"],
            signatureData: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8DwHwAFBQIAX8jx0gAAAABJRU5ErkJggg==",
            gpsLat: 47.6542,
            gpsLng: -122.3015,
            gpsTimestamp: new Date('2024-12-20T14:45:00Z').toISOString(),
            completionNotes: "Installed without issues. Customer requested business card for future service.",
            completedAt: new Date('2024-12-20T14:45:00Z').toISOString(),
            customerSatisfaction: 5,
        },
        {
            orderId: 3,
            subcontractorId: 3,
            timeSlotId: 3,
            completionPhotos: ["https://example.com/photos/job3-photo1.jpg", "https://example.com/photos/job3-photo2.jpg", "https://example.com/photos/job3-photo3.jpg", "https://example.com/photos/job3-photo4.jpg"],
            signatureData: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
            gpsLat: 47.5385,
            gpsLng: -122.3739,
            gpsTimestamp: new Date('2024-12-21T09:15:00Z').toISOString(),
            completionNotes: null,
            completedAt: new Date('2024-12-21T09:15:00Z').toISOString(),
            customerSatisfaction: 4,
        },
        {
            orderId: 4,
            subcontractorId: 4,
            timeSlotId: 4,
            completionPhotos: ["https://example.com/photos/job4-photo1.jpg", "https://example.com/photos/job4-photo2.jpg"],
            signatureData: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==",
            gpsLat: 47.6205,
            gpsLng: -122.3493,
            gpsTimestamp: new Date('2024-12-21T13:30:00Z').toISOString(),
            completionNotes: "Had to troubleshoot connection issues. Resolved after 30 minutes.",
            completedAt: new Date('2024-12-21T13:30:00Z').toISOString(),
            customerSatisfaction: 4,
        },
        {
            orderId: 5,
            subcontractorId: 5,
            timeSlotId: 5,
            completionPhotos: ["https://example.com/photos/job5-photo1.jpg", "https://example.com/photos/job5-photo2.jpg", "https://example.com/photos/job5-photo3.jpg"],
            signatureData: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+P+/HgAFhAJ/wlseKgAAAABJRU5ErkJggg==",
            gpsLat: 47.6815,
            gpsLng: -122.2087,
            gpsTimestamp: new Date('2024-12-22T11:00:00Z').toISOString(),
            completionNotes: "Customer requested additional service for next week. Provided estimate.",
            completedAt: new Date('2024-12-22T11:00:00Z').toISOString(),
            customerSatisfaction: 5,
        },
        {
            orderId: 6,
            subcontractorId: 6,
            timeSlotId: 6,
            completionPhotos: ["https://example.com/photos/job6-photo1.jpg", "https://example.com/photos/job6-photo2.jpg"],
            signatureData: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYGD4DwABBAEAW9EJRAAAAABJRU5ErkJggg==",
            gpsLat: 47.5635,
            gpsLng: -122.3952,
            gpsTimestamp: new Date('2024-12-22T15:20:00Z').toISOString(),
            completionNotes: null,
            completedAt: new Date('2024-12-22T15:20:00Z').toISOString(),
            customerSatisfaction: 4,
        },
        {
            orderId: 7,
            subcontractorId: 7,
            timeSlotId: 7,
            completionPhotos: ["https://example.com/photos/job7-photo1.jpg", "https://example.com/photos/job7-photo2.jpg", "https://example.com/photos/job7-photo3.jpg"],
            signatureData: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8CwHgAFAQIAujFCFwAAAABJRU5ErkJggg==",
            gpsLat: 47.6101,
            gpsLng: -122.2015,
            gpsTimestamp: new Date('2024-12-23T10:45:00Z').toISOString(),
            completionNotes: "Everything installed perfectly. Customer happy with service speed.",
            completedAt: new Date('2024-12-23T10:45:00Z').toISOString(),
            customerSatisfaction: 5,
        },
        {
            orderId: 8,
            subcontractorId: 8,
            timeSlotId: 8,
            completionPhotos: ["https://example.com/photos/job8-photo1.jpg", "https://example.com/photos/job8-photo2.jpg"],
            signatureData: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wHwAEhAJAGJtkxQAAAABJRU5ErkJggg==",
            gpsLat: 47.6425,
            gpsLng: -122.3158,
            gpsTimestamp: new Date('2024-12-23T14:00:00Z').toISOString(),
            completionNotes: null,
            completedAt: new Date('2024-12-23T14:00:00Z').toISOString(),
            customerSatisfaction: null,
        },
        {
            orderId: 9,
            subcontractorId: 9,
            timeSlotId: 9,
            completionPhotos: ["https://example.com/photos/job9-photo1.jpg", "https://example.com/photos/job9-photo2.jpg", "https://example.com/photos/job9-photo3.jpg", "https://example.com/photos/job9-photo4.jpg"],
            signatureData: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5/hPwAICAP/pMvKHwAAAABJRU5ErkJggg==",
            gpsLat: 47.5892,
            gpsLng: -122.3847,
            gpsTimestamp: new Date('2024-12-24T09:30:00Z').toISOString(),
            completionNotes: "Minor issue with mounting bracket. Resolved with spare part from truck.",
            completedAt: new Date('2024-12-24T09:30:00Z').toISOString(),
            customerSatisfaction: 4,
        },
        {
            orderId: 10,
            subcontractorId: 10,
            timeSlotId: 10,
            completionPhotos: ["https://example.com/photos/job10-photo1.jpg", "https://example.com/photos/job10-photo2.jpg"],
            signatureData: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPj/HwAChQGA3Y9CFQAAAABJRU5ErkJggg==",
            gpsLat: 47.6712,
            gpsLng: -122.2345,
            gpsTimestamp: new Date('2024-12-24T13:15:00Z').toISOString(),
            completionNotes: "Customer very satisfied. Provided 5-star review on the spot.",
            completedAt: new Date('2024-12-24T13:15:00Z').toISOString(),
            customerSatisfaction: 5,
        },
        {
            orderId: 11,
            subcontractorId: 1,
            timeSlotId: 11,
            completionPhotos: ["https://example.com/photos/job11-photo1.jpg", "https://example.com/photos/job11-photo2.jpg", "https://example.com/photos/job11-photo3.jpg"],
            signatureData: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8//+/PQAE+AL+2BShgQAAAABJRU5ErkJggg==",
            gpsLat: 47.5478,
            gpsLng: -122.3612,
            gpsTimestamp: new Date('2024-12-25T10:00:00Z').toISOString(),
            completionNotes: null,
            completedAt: new Date('2024-12-25T10:00:00Z').toISOString(),
            customerSatisfaction: 3,
        },
        {
            orderId: 12,
            subcontractorId: 2,
            timeSlotId: 12,
            completionPhotos: ["https://example.com/photos/job12-photo1.jpg", "https://example.com/photos/job12-photo2.jpg"],
            signatureData: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhAGA7BoX+wAAAABJRU5ErkJggg==",
            gpsLat: 47.6235,
            gpsLng: -122.3289,
            gpsTimestamp: new Date('2024-12-25T14:30:00Z').toISOString(),
            completionNotes: "Installation completed ahead of schedule. Customer pleased with efficiency.",
            completedAt: new Date('2024-12-25T14:30:00Z').toISOString(),
            customerSatisfaction: 5,
        },
        {
            orderId: 13,
            subcontractorId: 3,
            timeSlotId: 13,
            completionPhotos: ["https://example.com/photos/job13-photo1.jpg", "https://example.com/photos/job13-photo2.jpg", "https://example.com/photos/job13-photo3.jpg"],
            signatureData: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8DwHwAFBQIAXzPx0AAAAABJRU5ErkJggg==",
            gpsLat: 47.6589,
            gpsLng: -122.3124,
            gpsTimestamp: new Date('2024-12-26T11:45:00Z').toISOString(),
            completionNotes: "Customer requested follow-up maintenance visit in 6 months.",
            completedAt: new Date('2024-12-26T11:45:00Z').toISOString(),
            customerSatisfaction: 4,
        },
        {
            orderId: 14,
            subcontractorId: 4,
            timeSlotId: 14,
            completionPhotos: ["https://example.com/photos/job14-photo1.jpg", "https://example.com/photos/job14-photo2.jpg"],
            signatureData: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPj/HwAChAGA4F8lZwAAAABJRU5ErkJggg==",
            gpsLat: 47.5723,
            gpsLng: -122.3891,
            gpsTimestamp: new Date('2024-12-26T15:00:00Z').toISOString(),
            completionNotes: null,
            completedAt: new Date('2024-12-26T15:00:00Z').toISOString(),
            customerSatisfaction: null,
        },
        {
            orderId: 15,
            subcontractorId: 5,
            timeSlotId: 15,
            completionPhotos: ["https://example.com/photos/job15-photo1.jpg", "https://example.com/photos/job15-photo2.jpg", "https://example.com/photos/job15-photo3.jpg"],
            signatureData: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/BqCPYgAAAABJRU5ErkJggg==",
            gpsLat: 47.6958,
            gpsLng: -122.2178,
            gpsTimestamp: new Date('2024-12-26T16:30:00Z').toISOString(),
            completionNotes: "Excellent customer interaction. They mentioned they would refer us to neighbors.",
            completedAt: new Date('2024-12-26T16:30:00Z').toISOString(),
            customerSatisfaction: 5,
        },
    ];

    await db.insert(jobCompletions).values(sampleJobCompletions);
    
    console.log('✅ Job completions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});