import { db } from '@/db';
import { orders } from '@/db/schema';

async function main() {
    const sampleOrders = [
        {
            customerName: 'Sarah Johnson',
            customerEmail: 'sarah.johnson@email.com',
            customerPhone: '206-555-0123',
            address: '1234 Pike St',
            city: 'Seattle',
            locationLat: 47.6097,
            locationLng: -122.3331,
            serviceType: 'Installation',
            inventoryItems: [
                { name: 'Router TP-Link AX3000', quantity: 1, inStock: true },
                { name: 'Cable Box DVR', quantity: 2, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'high',
            estimatedDuration: 90,
            specialInstructions: 'Call before arrival',
            status: 'scheduled',
            createdAt: new Date('2024-12-20T09:30:00Z').toISOString(),
            dueDate: '2024-12-23',
        },
        {
            customerName: 'Michael Chen',
            customerEmail: 'michael.chen@email.com',
            customerPhone: '425-555-0234',
            address: '5678 Broadway Ave',
            city: 'Bellevue',
            locationLat: 47.6101,
            locationLng: -122.2015,
            serviceType: 'Delivery',
            inventoryItems: [
                { name: 'Smart Thermostat', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'medium',
            estimatedDuration: 30,
            specialInstructions: null,
            status: 'unassigned',
            createdAt: new Date('2024-12-21T14:15:00Z').toISOString(),
            dueDate: '2024-12-24',
        },
        {
            customerName: 'Emily Rodriguez',
            customerEmail: 'emily.rodriguez@email.com',
            customerPhone: '206-555-0345',
            address: '910 Main St Apt 204',
            city: 'Seattle',
            locationLat: 47.6205,
            locationLng: -122.3493,
            serviceType: 'Repair',
            inventoryItems: [
                { name: 'Modem DOCSIS 3.1', quantity: 1, inStock: false }
            ],
            inventoryStatus: 'pending',
            priority: 'urgent',
            estimatedDuration: 60,
            specialInstructions: 'Use side entrance',
            status: 'claimed',
            createdAt: new Date('2024-12-22T08:00:00Z').toISOString(),
            dueDate: '2024-12-23',
        },
        {
            customerName: 'David Thompson',
            customerEmail: 'david.thompson@email.com',
            customerPhone: '253-555-0456',
            address: '2345 Pacific Ave',
            city: 'Tacoma',
            locationLat: 47.2529,
            locationLng: -122.4443,
            serviceType: 'Installation',
            inventoryItems: [
                { name: 'Security Camera 4K', quantity: 3, inStock: true },
                { name: 'Router TP-Link AX3000', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'medium',
            estimatedDuration: 120,
            specialInstructions: 'Dog on property',
            status: 'in_progress',
            createdAt: new Date('2024-12-19T10:45:00Z').toISOString(),
            dueDate: '2024-12-22',
        },
        {
            customerName: 'Jessica Martinez',
            customerEmail: 'jessica.martinez@email.com',
            customerPhone: '425-555-0567',
            address: '7890 NE 8th St',
            city: 'Bellevue',
            locationLat: 47.6156,
            locationLng: -122.1896,
            serviceType: 'Delivery',
            inventoryItems: [
                { name: 'Cable Box DVR', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'low',
            estimatedDuration: 45,
            specialInstructions: null,
            status: 'completed',
            createdAt: new Date('2024-12-18T13:20:00Z').toISOString(),
            dueDate: '2024-12-20',
        },
        {
            customerName: 'Robert Kim',
            customerEmail: 'robert.kim@email.com',
            customerPhone: '206-555-0678',
            address: '3456 15th Ave E',
            city: 'Seattle',
            locationLat: 47.6423,
            locationLng: -122.3117,
            serviceType: 'Installation',
            inventoryItems: [
                { name: 'Router TP-Link AX3000', quantity: 2, inStock: true },
                { name: 'Modem DOCSIS 3.1', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'partial',
            priority: 'high',
            estimatedDuration: 90,
            specialInstructions: 'Gate code 1234',
            status: 'unassigned',
            createdAt: new Date('2024-12-23T11:00:00Z').toISOString(),
            dueDate: '2024-12-26',
        },
        {
            customerName: 'Amanda Foster',
            customerEmail: 'amanda.foster@email.com',
            customerPhone: '425-555-0789',
            address: '4567 156th Ave NE',
            city: 'Redmond',
            locationLat: 47.6740,
            locationLng: -122.1215,
            serviceType: 'Repair',
            inventoryItems: [
                { name: 'Smart Thermostat', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'medium',
            estimatedDuration: 45,
            specialInstructions: 'Call before arrival',
            status: 'scheduled',
            createdAt: new Date('2024-12-21T16:30:00Z').toISOString(),
            dueDate: '2024-12-24',
        },
        {
            customerName: 'Christopher Lee',
            customerEmail: 'christopher.lee@email.com',
            customerPhone: '206-555-0890',
            address: '5678 Queen Anne Ave N',
            city: 'Seattle',
            locationLat: 47.6365,
            locationLng: -122.3567,
            serviceType: 'Delivery',
            inventoryItems: [
                { name: 'Security Camera 4K', quantity: 2, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'low',
            estimatedDuration: 30,
            specialInstructions: null,
            status: 'claimed',
            createdAt: new Date('2024-12-22T09:15:00Z').toISOString(),
            dueDate: '2024-12-25',
        },
        {
            customerName: 'Nicole Anderson',
            customerEmail: 'nicole.anderson@email.com',
            customerPhone: '425-555-0901',
            address: '6789 100th Ave NE',
            city: 'Bellevue',
            locationLat: 47.6100,
            locationLng: -122.1851,
            serviceType: 'Installation',
            inventoryItems: [
                { name: 'Cable Box DVR', quantity: 1, inStock: false },
                { name: 'Router TP-Link AX3000', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'partial',
            priority: 'medium',
            estimatedDuration: 60,
            specialInstructions: 'Apartment buzzer broken, call on arrival',
            status: 'unassigned',
            createdAt: new Date('2024-12-23T14:45:00Z').toISOString(),
            dueDate: '2024-12-27',
        },
        {
            customerName: 'Matthew White',
            customerEmail: 'matthew.white@email.com',
            customerPhone: '253-555-1012',
            address: '7890 S 12th St',
            city: 'Tacoma',
            locationLat: 47.2445,
            locationLng: -122.4412,
            serviceType: 'Repair',
            inventoryItems: [
                { name: 'Modem DOCSIS 3.1', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'high',
            estimatedDuration: 90,
            specialInstructions: 'Ring doorbell twice',
            status: 'in_progress',
            createdAt: new Date('2024-12-20T12:00:00Z').toISOString(),
            dueDate: '2024-12-23',
        },
        {
            customerName: 'Lauren Davis',
            customerEmail: 'lauren.davis@email.com',
            customerPhone: '425-555-1123',
            address: '8901 Colby Ave',
            city: 'Everett',
            locationLat: 47.9790,
            locationLng: -122.2021,
            serviceType: 'Delivery',
            inventoryItems: [
                { name: 'Smart Thermostat', quantity: 2, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'medium',
            estimatedDuration: 45,
            specialInstructions: null,
            status: 'completed',
            createdAt: new Date('2024-12-19T15:30:00Z').toISOString(),
            dueDate: '2024-12-21',
        },
        {
            customerName: 'Daniel Brown',
            customerEmail: 'daniel.brown@email.com',
            customerPhone: '206-555-1234',
            address: '9012 Greenwood Ave N',
            city: 'Seattle',
            locationLat: 47.6890,
            locationLng: -122.3544,
            serviceType: 'Installation',
            inventoryItems: [
                { name: 'Security Camera 4K', quantity: 1, inStock: true },
                { name: 'Router TP-Link AX3000', quantity: 1, inStock: true },
                { name: 'Cable Box DVR', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'urgent',
            estimatedDuration: 120,
            specialInstructions: 'Use back door entrance',
            status: 'scheduled',
            createdAt: new Date('2024-12-21T08:45:00Z').toISOString(),
            dueDate: '2024-12-24',
        },
        {
            customerName: 'Stephanie Wilson',
            customerEmail: 'stephanie.wilson@email.com',
            customerPhone: '425-555-1345',
            address: '1123 148th Ave SE',
            city: 'Bellevue',
            locationLat: 47.5845,
            locationLng: -122.1412,
            serviceType: 'Repair',
            inventoryItems: [
                { name: 'Router TP-Link AX3000', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'low',
            estimatedDuration: 45,
            specialInstructions: null,
            status: 'cancelled',
            createdAt: new Date('2024-12-22T10:00:00Z').toISOString(),
            dueDate: '2024-12-25',
        },
        {
            customerName: 'Kevin Garcia',
            customerEmail: 'kevin.garcia@email.com',
            customerPhone: '206-555-1456',
            address: '2234 California Ave SW',
            city: 'Seattle',
            locationLat: 47.5634,
            locationLng: -122.3867,
            serviceType: 'Delivery',
            inventoryItems: [
                { name: 'Modem DOCSIS 3.1', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'medium',
            estimatedDuration: 30,
            specialInstructions: 'Leave at front desk',
            status: 'unassigned',
            createdAt: new Date('2024-12-23T13:20:00Z').toISOString(),
            dueDate: '2024-12-26',
        },
        {
            customerName: 'Rachel Martinez',
            customerEmail: 'rachel.martinez@email.com',
            customerPhone: '425-555-1567',
            address: '3345 NE Sunset Blvd',
            city: 'Redmond',
            locationLat: 47.6723,
            locationLng: -122.1189,
            serviceType: 'Installation',
            inventoryItems: [
                { name: 'Smart Thermostat', quantity: 1, inStock: false },
                { name: 'Security Camera 4K', quantity: 2, inStock: true }
            ],
            inventoryStatus: 'pending',
            priority: 'high',
            estimatedDuration: 90,
            specialInstructions: 'Gate code 5678',
            status: 'claimed',
            createdAt: new Date('2024-12-20T11:30:00Z').toISOString(),
            dueDate: '2024-12-23',
        },
        {
            customerName: 'Brian Taylor',
            customerEmail: 'brian.taylor@email.com',
            customerPhone: '253-555-1678',
            address: '4456 6th Ave',
            city: 'Tacoma',
            locationLat: 47.2534,
            locationLng: -122.4398,
            serviceType: 'Repair',
            inventoryItems: [
                { name: 'Cable Box DVR', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'medium',
            estimatedDuration: 60,
            specialInstructions: null,
            status: 'unassigned',
            createdAt: new Date('2024-12-22T15:00:00Z').toISOString(),
            dueDate: '2024-12-26',
        },
        {
            customerName: 'Melissa Thomas',
            customerEmail: 'melissa.thomas@email.com',
            customerPhone: '425-555-1789',
            address: '5567 Broadway',
            city: 'Everett',
            locationLat: 47.9801,
            locationLng: -122.1978,
            serviceType: 'Delivery',
            inventoryItems: [
                { name: 'Router TP-Link AX3000', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'low',
            estimatedDuration: 30,
            specialInstructions: 'Call before arrival',
            status: 'completed',
            createdAt: new Date('2024-12-19T09:00:00Z').toISOString(),
            dueDate: '2024-12-21',
        },
        {
            customerName: 'Jason Hernandez',
            customerEmail: 'jason.hernandez@email.com',
            customerPhone: '206-555-1890',
            address: '6678 Phinney Ave N',
            city: 'Seattle',
            locationLat: 47.6712,
            locationLng: -122.3556,
            serviceType: 'Installation',
            inventoryItems: [
                { name: 'Security Camera 4K', quantity: 3, inStock: true },
                { name: 'Modem DOCSIS 3.1', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'partial',
            priority: 'high',
            estimatedDuration: 120,
            specialInstructions: 'Dog on property - very friendly',
            status: 'scheduled',
            createdAt: new Date('2024-12-21T12:15:00Z').toISOString(),
            dueDate: '2024-12-24',
        },
        {
            customerName: 'Ashley Moore',
            customerEmail: 'ashley.moore@email.com',
            customerPhone: '425-555-1901',
            address: '7789 Main St',
            city: 'Bellevue',
            locationLat: 47.6123,
            locationLng: -122.1867,
            serviceType: 'Repair',
            inventoryItems: [
                { name: 'Smart Thermostat', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'urgent',
            estimatedDuration: 45,
            specialInstructions: 'Ring bell for unit 302',
            status: 'in_progress',
            createdAt: new Date('2024-12-23T08:30:00Z').toISOString(),
            dueDate: '2024-12-24',
        },
        {
            customerName: 'Ryan Jackson',
            customerEmail: 'ryan.jackson@email.com',
            customerPhone: '206-555-2012',
            address: '8890 23rd Ave S',
            city: 'Seattle',
            locationLat: 47.5445,
            locationLng: -122.3012,
            serviceType: 'Delivery',
            inventoryItems: [
                { name: 'Cable Box DVR', quantity: 2, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'medium',
            estimatedDuration: 45,
            specialInstructions: null,
            status: 'unassigned',
            createdAt: new Date('2024-12-22T14:00:00Z').toISOString(),
            dueDate: '2024-12-25',
        },
        {
            customerName: 'Michelle Martin',
            customerEmail: 'michelle.martin@email.com',
            customerPhone: '425-555-2123',
            address: '9901 Redmond Way',
            city: 'Redmond',
            locationLat: 47.6698,
            locationLng: -122.1256,
            serviceType: 'Installation',
            inventoryItems: [
                { name: 'Router TP-Link AX3000', quantity: 1, inStock: true },
                { name: 'Security Camera 4K', quantity: 1, inStock: false }
            ],
            inventoryStatus: 'partial',
            priority: 'medium',
            estimatedDuration: 90,
            specialInstructions: 'Park in visitor lot',
            status: 'claimed',
            createdAt: new Date('2024-12-20T10:00:00Z').toISOString(),
            dueDate: '2024-12-23',
        },
        {
            customerName: 'Steven Thompson',
            customerEmail: 'steven.thompson@email.com',
            customerPhone: '253-555-2234',
            address: '1012 Commerce St',
            city: 'Tacoma',
            locationLat: 47.2456,
            locationLng: -122.4367,
            serviceType: 'Repair',
            inventoryItems: [
                { name: 'Modem DOCSIS 3.1', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'low',
            estimatedDuration: 60,
            specialInstructions: null,
            status: 'unassigned',
            createdAt: new Date('2024-12-23T11:45:00Z').toISOString(),
            dueDate: '2024-12-27',
        },
        {
            customerName: 'Kimberly White',
            customerEmail: 'kimberly.white@email.com',
            customerPhone: '425-555-2345',
            address: '1123 Rucker Ave',
            city: 'Everett',
            locationLat: 47.9823,
            locationLng: -122.2045,
            serviceType: 'Delivery',
            inventoryItems: [
                { name: 'Smart Thermostat', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'medium',
            estimatedDuration: 30,
            specialInstructions: 'Leave with neighbor if not home',
            status: 'completed',
            createdAt: new Date('2024-12-18T16:00:00Z').toISOString(),
            dueDate: '2024-12-20',
        },
        {
            customerName: 'Joshua Harris',
            customerEmail: 'joshua.harris@email.com',
            customerPhone: '206-555-2456',
            address: '2234 Ballard Ave NW',
            city: 'Seattle',
            locationLat: 47.6656,
            locationLng: -122.3834,
            serviceType: 'Installation',
            inventoryItems: [
                { name: 'Cable Box DVR', quantity: 1, inStock: true },
                { name: 'Router TP-Link AX3000', quantity: 2, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'high',
            estimatedDuration: 90,
            specialInstructions: 'Call before arrival',
            status: 'scheduled',
            createdAt: new Date('2024-12-21T09:30:00Z').toISOString(),
            dueDate: '2024-12-24',
        },
        {
            customerName: 'Jennifer Clark',
            customerEmail: 'jennifer.clark@email.com',
            customerPhone: '425-555-2567',
            address: '3345 116th Ave NE',
            city: 'Bellevue',
            locationLat: 47.6234,
            locationLng: -122.1778,
            serviceType: 'Repair',
            inventoryItems: [
                { name: 'Security Camera 4K', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'medium',
            estimatedDuration: 45,
            specialInstructions: null,
            status: 'unassigned',
            createdAt: new Date('2024-12-22T13:00:00Z').toISOString(),
            dueDate: '2024-12-25',
        },
        {
            customerName: 'Andrew Lewis',
            customerEmail: 'andrew.lewis@email.com',
            customerPhone: '206-555-2678',
            address: '4456 Alki Ave SW',
            city: 'Seattle',
            locationLat: 47.5801,
            locationLng: -122.4078,
            serviceType: 'Delivery',
            inventoryItems: [
                { name: 'Modem DOCSIS 3.1', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'low',
            estimatedDuration: 30,
            specialInstructions: 'Beachfront property, parking limited',
            status: 'claimed',
            createdAt: new Date('2024-12-23T10:15:00Z').toISOString(),
            dueDate: '2024-12-26',
        },
        {
            customerName: 'Elizabeth Robinson',
            customerEmail: 'elizabeth.robinson@email.com',
            customerPhone: '425-555-2789',
            address: '5567 166th Ave NE',
            city: 'Redmond',
            locationLat: 47.6756,
            locationLng: -122.1123,
            serviceType: 'Installation',
            inventoryItems: [
                { name: 'Router TP-Link AX3000', quantity: 1, inStock: false }
            ],
            inventoryStatus: 'pending',
            priority: 'medium',
            estimatedDuration: 60,
            specialInstructions: 'Gate code 9876',
            status: 'unassigned',
            createdAt: new Date('2024-12-20T14:30:00Z').toISOString(),
            dueDate: '2024-12-24',
        },
        {
            customerName: 'Benjamin Walker',
            customerEmail: 'benjamin.walker@email.com',
            customerPhone: '253-555-2890',
            address: '6678 S Pine St',
            city: 'Tacoma',
            locationLat: 47.2389,
            locationLng: -122.4501,
            serviceType: 'Repair',
            inventoryItems: [
                { name: 'Smart Thermostat', quantity: 1, inStock: true },
                { name: 'Cable Box DVR', quantity: 1, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'high',
            estimatedDuration: 90,
            specialInstructions: 'Use side entrance',
            status: 'in_progress',
            createdAt: new Date('2024-12-21T11:00:00Z').toISOString(),
            dueDate: '2024-12-23',
        },
        {
            customerName: 'Samantha Young',
            customerEmail: 'samantha.young@email.com',
            customerPhone: '425-555-2901',
            address: '7789 Colby Ave',
            city: 'Everett',
            locationLat: 47.9867,
            locationLng: -122.1989,
            serviceType: 'Delivery',
            inventoryItems: [
                { name: 'Security Camera 4K', quantity: 2, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'medium',
            estimatedDuration: 45,
            specialInstructions: null,
            status: 'completed',
            createdAt: new Date('2024-12-19T12:30:00Z').toISOString(),
            dueDate: '2024-12-21',
        },
        {
            customerName: 'Tyler Allen',
            customerEmail: 'tyler.allen@email.com',
            customerPhone: '206-555-3012',
            address: '8890 Lake City Way NE',
            city: 'Seattle',
            locationLat: 47.7234,
            locationLng: -122.2945,
            serviceType: 'Installation',
            inventoryItems: [
                { name: 'Modem DOCSIS 3.1', quantity: 1, inStock: true },
                { name: 'Router TP-Link AX3000', quantity: 1, inStock: true },
                { name: 'Cable Box DVR', quantity: 2, inStock: true }
            ],
            inventoryStatus: 'available',
            priority: 'urgent',
            estimatedDuration: 120,
            specialInstructions: 'Business location, ask for manager',
            status: 'scheduled',
            createdAt: new Date('2024-12-22T08:00:00Z').toISOString(),
            dueDate: '2024-12-25',
        }
    ];

    await db.insert(orders).values(sampleOrders);
    
    console.log('✅ Orders seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});